version: 1.0.{build}
os: Visual Studio 2015
shallow_clone: true
install:
- cmd: echo %DNX_BUILD_VERSION%
- cmd: echo %WEBPROJ_ENABLEBETA8RENAMES%
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm update-self
- cmd: dnvm install 1.0.0-rc1-update1
- cmd: dnu restore --quiet --parallel
build_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\src\CryptoSwift.Console
- cmd: dnu build
artifacts:
  - path: '**\*.nupkg'
cache:
  - C:\Users\appveyor\.dnx\packages
test_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\test\CryptoSwift.Tests
- cmd: dnx tests
environment:
  DNX_BUILD_VERSION: rc1-update1-%APPVEYOR_BUILD_NUMBER%
init:
#- ps: npm install -g bower

